### ISSUE TITLE
Compilation of the unify-matter-bridge failed

### ISSUE THREAD

**Issue by BurievSardor** [SiliconLabs/matter#138]
### Description of the issue

I followed https://siliconlabs.github.io/matter/latest/unify/matter-bridge/readme_building.html. 
Cloned matter from https://github.com/SiliconLabs/matter.git (version: v2.2.0-1.2)
But the Matter environment activation  failed. I fixed it manually modifying scripts/setup/constraints.txt (https://github.com/project-chip/connectedhomeip/pull/30987/commits/b867178db386520ca358e9079d9c09464bab5002) . After that I successfully activated the matter environment.

But Compilation of the unify-matter-bridge failed:

(base) root@71549e98dd1a:/matter/silabs_examples/unify-matter-bridge/linux# ninja -C out/arm64
ninja: Entering directory `out/arm64'
[15/814] ACTION //:get_chip_version(//third_party/connectedhomeip/build/toolchain/linux:linux_arm64_gcc)
FAILED: gen/include/chip_version.hpp
python /matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py gen/include/chip_version.hpp
Traceback (most recent call last):
  File "/matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py", line 53, in <module>
    generate_git_info(output_file)
  File "/matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py", line 19, in generate_git_info
    version = subprocess.check_output(['git', 'describe', '--tags'], text=True, stderr=subprocess.DEVNULL).strip().split('-', 1)[1]
IndexError: list index out of range
[20/814] ACTION //third_party/connectedhomeip/src/lib/asn1:gen_a...ird_party/connectedhomeip/build/toolchain/linux:linux_arm64_gcc
ninja: build stopped: subcommand failed.

WSL2
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

### Steps to reproduce the issue

```bash
While compiling the unify-matter-bridge
```

### Device type(s) and network topology

 unify-matter-bridge

### SMG version

release_2.2.0-1.2

### Protocol(s)

Wi-Fi

### Hardware platform(s)

Host Linux 

### Captured data or logs

(base) root@71549e98dd1a:/matter# cd silabs_examples/unify-matter-bridge/linux/
(base) root@71549e98dd1a:/matter/silabs_examples/unify-matter-bridge/linux# gn gen out/arm64 --args='target_cpu="arm64"'
Done. Made 269 targets from 218 files in 737ms
(base) root@71549e98dd1a:/matter/silabs_examples/unify-matter-bridge/linux# ninja -C out/arm64
ninja: Entering directory `out/arm64'
[15/814] ACTION //:get_chip_version(//third_party/connectedhomeip/build/toolchain/linux:linux_arm64_gcc)
FAILED: gen/include/chip_version.hpp
python /matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py gen/include/chip_version.hpp
Traceback (most recent call last):
  File "/matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py", line 53, in <module>
    generate_git_info(output_file)
  File "/matter/silabs_examples/unify-matter-bridge/scripts/gen_version_info.py", line 19, in generate_git_info
    version = subprocess.check_output(['git', 'describe', '--tags'], text=True, stderr=subprocess.DEVNULL).strip().split('-', 1)[1]
IndexError: list index out of range
[20/814] ACTION //third_party/connectedhomeip/src/lib/asn1:gen_a...ird_party/connectedhomeip/build/toolchain/linux:linux_arm64_gcc
ninja: build stopped: subcommand failed.

**Comment by BurievSardor** [comment]
had to modify the source code to compile unify-matter-bridge successfully.
[unify.txt](https://github.com/SiliconLabs/matter/files/13688389/unify.txt)

"subprocess.check_output(['git', 'describe', '--tags'], text=True, stderr=subprocess.DEVNULL).strip()" is returning "latest".

@tecimovic  @rerasool  @jepenven-silabs  @jmartinez-silabs
